//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_labellingflora : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean RightTriggerPressed
        {
            get
            {
                return SteamVR_Actions.labellingflora_RightTriggerPressed;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightMenuButtonPressed
        {
            get
            {
                return SteamVR_Actions.labellingflora_RightMenuButtonPressed;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightTrackpadPressed
        {
            get
            {
                return SteamVR_Actions.labellingflora_RightTrackpadPressed;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RightTrackpadPosition
        {
            get
            {
                return SteamVR_Actions.labellingflora_RightTrackpadPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftTriggerPressed
        {
            get
            {
                return SteamVR_Actions.labellingflora_LeftTriggerPressed;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftTrackpadPressed
        {
            get
            {
                return SteamVR_Actions.labellingflora_LeftTrackpadPressed;
            }
        }
        
        public virtual SteamVR_Action_Vector2 LeftTrackpadPosition
        {
            get
            {
                return SteamVR_Actions.labellingflora_LeftTrackpadPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftMenuButtonPressed
        {
            get
            {
                return SteamVR_Actions.labellingflora_LeftMenuButtonPressed;
            }
        }
    }
}
